<a href="https://colab.research.google.com/github/vvnssrnath2002/vvnssrnath2002/blob/main/python_for_ml_class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello,world")

Hello,world


In [ ]:
print("Hey",10,2.2,"Hello")

Hey 10 2.2 Hello


In [ ]:
s=input("Hello Python")

Hello PythonHai


In [ ]:
name=input("What is your name? ")
print("Hello",name.capitalize())
age=input("How old are you? ")
print("You are",age,"years old")



What is your name? Raghunath
Hello Raghunath
How old are you? 21
You are 21 years old


In [ ]:
s="saurabh"
t=s.capitalize()
print(t)



Saurabh


In [ ]:
s="This is a string"
a=2
b=2.4

type(s)


int

In [ ]:
kg=float(input("Enter the weight in kg:"))
lbs = kg * 2.2046
print(f"The {kg} kilograms to lbs is: {lbs}")

Enter the weight in kg:26.7
The 26.7 kilograms to lbs is: 58.86282


In [ ]:
r=float(input("Enter the radius:"))
pi=3.14
C=2 * pi * r
print(C)


Enter the radius:5
31.400000000000002


In [ ]:
num = 10
num = num * 3
num = num + 6
num = num // 3
number = num - 10
print(number)


2


In [ ]:
a=float(input("Enter first number"))
b=float(input("Enter second number"))
c=a*b
print(f"Product= {c}")

Enter first number3
Enter second number4
Product= 12.0


In [ ]:
years=int(input("Enter the age of user:"))
days = years * 365
hours = days * 24
minutes = hours * 3600
seconds = minutes * 60
print(f'Age in Days is = {days}')
print(f'Age in Hours is = {hours}')
print(f'Age in Minutes is = {minutes}')
print(f'Age in Seconds is = {seconds}')

Enter the age of user:22
Age in Days is = 8030
Age in Hours is = 192720
Age in Minutes is = 693792000
Age in Seconds is = 41627520000


In [ ]:
price = int(input("Enter the price:"))
percent = int(input("Enter the percentage:"))
tip = price * percent/100
tip = round(tip,2)
print(tip)

Enter the price:400
Enter the percentage:5
20.0


In [ ]:
hrs = float(input("Enter the number of hours:"))
rph = float(input("Enter the rate per hour of worker:"))
GrossPay = hrs * rph
print(GrossPay)

Enter the number of hours:3.5
Enter the rate per hour of worker:45.5
159.25


In [ ]:
hrs = float(input("Enter number of hours:"))
rate = float(input("Enter the rate:"))
pay = hrs * rate
if(hrs>40):
   pay = (40 * rate) + (hrs-40) * rate * 1.5
else:
  pay = pay
print(pay)

Enter number of hours:45
Enter the rate:10
475.0


In [ ]:
inp = float(input("Enter temperature in Celsius:"))
try:
  print("Farenheit")
except:
  print("Enter temperature in digits/numbers")

Enter temperature in Celsius:30
Farenheit


In [ ]:
#Car - Ensurance
#Goal - Car Ensurance Calculation based on the following data
#This is fictional car insurance company call

market_price = float(input("Enter market price:"))
gender = input("Enter the gender:")
def calculate_insurance_premium(market_price,gender):
   if gender.lower() == "male":
    age = int(input("Enter your age:"))
    if age <=26:
      premium = (23/100)*market_price
    else:
      premium = (9/100) * market_price

  elif gender.lower() == "female":
    is_sports_car = input("Is your car a sports car?(yes/no):")
    if is_sports_car.lower() == "yes":
      premium = (21/100)*market_price
    else:
      premium = (10/100)*market_price
  else:
    print("Invalid gender input.")

  return premium

premium = calculate_insurance_premium(market_price, gender)
print("The insurance premium is:", premium)


Enter market price:20000
Enter the gender:male
Enter your age:30
The insurance premium is: 1800.0


In [ ]:
smallest_so_far = 100
print('Before',smallest_so_far)
for the_num in [9,41,12,3,74,15]:
  if the_num < smallest_so_far:
    smallest_so_far = the_num
  print('smallest_so_far',the_num)

print('After',smallest_so_far)


Before 100
smallest_so_far 9
smallest_so_far 41
smallest_so_far 12
smallest_so_far 3
smallest_so_far 74
smallest_so_far 15
After 3


In [ ]:
zork = 0
print('Before',zork)
for thing in [9,41,12,3,74,15]:
  zork = zork+1
  print(zork, thing)
print('After', zork)

Before 0
1 9
2 41
3 12
4 3
5 74
6 15
After 6


In [ ]:
num_list = []
n=int(input("Enter the number of elements in the list:"))
for i in range(n):
  num = int(input("Enter number:"))
  num_list.append(num)
sum_of_elements = sum(num_list)
print("Sum of all elements:",sum_of_elements)

Enter the number of elements in the list:5
Enter number:6
Enter number:6
Enter number:3
Enter number:4
Enter number:8
Sum of all elements: 27


In [ ]:
#largest so far
largest_so_far = -1
print("Before",largest_so_far)
print("Current\tLargest so far")
for the_num in [9,41,12,3,74,15]:
  if the_num > largest_so_far:
    largest_so_far = the_num
  print(largest_so_far,"\t",the_num)
print("After",largest_so_far)

Before -1
Current	Largest so far
9 	 9
41 	 41
41 	 12
41 	 3
74 	 74
74 	 15
After 74


In [ ]:
def computepay(hrs,rate):
  pay = hrs * rate
  if(hrs>40):
      pay = (40 * rate) + (hrs-40) * rate * 1.5
  else:
      pay = pay
  print(pay)
computepay(40,10)

400


In [ ]:
list1 = [1,2,"Hello","Hi"]
print(list1)

[1, 2, 'Hello', 'Hi']


In [ ]:
l1 = [1,4,5,7,4,15]
print(l1)

[1, 4, 5, 7, 4, 15]


In [ ]:
l1[2:4]

[5, 7]

In [ ]:
l1[:4]

[1, 4, 5, 7]

In [ ]:
l1[:-1]

[1, 4, 5, 7, 4]

In [ ]:
print(l1 + list1)

[1, 4, 5, 7, 4, 15, 1, 2, 'Hello', 'Hi']


In [ ]:
print(list1 * 3)

[1, 2, 'Hello', 'Hi', 1, 2, 'Hello', 'Hi', 1, 2, 'Hello', 'Hi']


In [ ]:
l2=[23,24,25,["A","LPU",5],3,2,1]
l2[3][1][1]

'P'

In [ ]:
#lists are mutable
list3 = ['a','b','c','d']
list3[-1] = 'xyz'
list3

['a', 'b', 'c', 'xyz']

In [ ]:
list3.append("LPU")
list3

['a', 'b', 'c', 'xyz', 'LPU']

In [ ]:
list3.append(5)
list3


['a', 'b', 'c', 'xyz', 'LPU', 5, 5, 5, 5, 5]

In [ ]:
l1.extend(list3)
l1


[1, 4, 5, 7, 4, 15, 'a', 'b', 'c', 'xyz', 'LPU', 5, 5, 5, 5, 5]

In [ ]:
list3

['a', 'b', 'c', 'xyz', 'LPU', 5, 5, 5, 5, 5]

In [ ]:
t1 = (1,2,3,4)
print(t1)
print(type(t1))

(1, 2, 3, 4)
<class 'tuple'>


In [ ]:
t2 = (5)
print(type(t2))

<class 'int'>


In [ ]:
t2 = (5,)
print(type(t2))

<class 'tuple'>


In [ ]:
empty_list = []
print(type(empty_list))

<class 'list'>


In [ ]:
empty_tuple = ()
print(type(empty_tuple))

<class 'tuple'>


In [ ]:
empty_dict = {}
print(type(empty_dict))

<class 'dict'>


In [ ]:
import random
random.randint(1,7)

6

In [ ]:
# Python program for jumbled words game.

# import random module
import random


# function for choosing random word.
def choose():
	# list of word
	words = ['rainbow', 'computer', 'science', 'programming',
			'mathematics', 'player', 'condition', 'reverse',
			'water', 'board', 'geeks']

	# choice() method randomly choose
	# any word from the list.
	pick = random.choice(words)

	return pick


# Function for shuffling the
# characters of the chosen word.
def jumble(word):
	# sample() method shuffling the characters of the word
	random_word = random.sample(word, len(word))

	# join() method join the elements
	# of the iterator(e.g. list) with particular character .
	jumbled = ''.join(random_word)
	return jumbled


# Function for showing final score.
def thank(p1n, p2n, p1, p2):
	print(p1n, 'Your score is :', p1)
	print(p2n, 'Your score is :', p2)

	# check_win() function calling
	check_win(p1n, p2n, p1, p2)

	print('Thanks for playing...')


# Function for declaring winner
def check_win(player1, player2, p1score, p2score):
	if p1score > p2score:
		print("winner is :", player1)
	elif p2score > p1score:
		print("winner is :", player2)
	else:
		print("Draw..Well Played guys..")


# Function for playing the game.
def play():
	# enter player1 and player2 name
	p1name = input("player 1, Please enter your name :")
	p2name = input("Player 2 , Please enter your name: ")

	# variable for counting score.
	pp1 = 0
	pp2 = 0

	# variable for counting turn
	turn = 0

	# keep looping
	while True:

		# choose() function calling
		picked_word = choose()

		# jumble() function calling
		qn = jumble(picked_word)
		print("jumbled word is :", qn)

		# checking turn is odd or even
		if turn % 2 == 0:

			# if turn no. is even
			# player1 turn
			print(p1name, 'Your Turn.')

			ans = input("what is in your mind? ")

			# checking ans is equal to picked_word or not
			if ans == picked_word:

				# incremented by 1
				pp1 += 1

				print('Your score is :', pp1)
				turn += 1

			else:
				print("Better luck next time ..")

				# player 2 turn
				print(p2name, 'Your turn.')

				ans = input('what is in your mind? ')

				if ans == picked_word:
					pp2 += 1
					print("Your Score is :", pp2)

				else:
					print("Better luck next time...correct word is :", picked_word)

				c = int(input("press 1 to continue and 0 to quit :"))

				# checking the c is equal to 0 or not
				# if c is equal to 0 then break out
				# of the while loop o/w keep looping.
				if c == 0:
					# thank() function calling
					thank(p1name, p2name, pp1, pp2)
					break

		else:

			# if turn no. is odd
			# player2 turn
			print(p2name, 'Your turn.')
			ans = input('what is in your mind? ')

			if ans == picked_word:
				pp2 += 1
				print("Your Score is :", pp2)
				turn += 1

			else:
				print("Better luck next time.. :")
				print(p1name, 'Your turn.')
				ans = input('what is in your mind? ')

				if ans == picked_word:
					pp1 += 1
					print("Your Score is :", pp1)

				else:
					print("Better luck next time...correct word is :", picked_word)

					c = int(input("press 1 to continue and 0 to quit :"))

					if c == 0:
						# thank() function calling
						thank(p1name, p2name, pp1, pp2)
						break

			c = int(input("press 1 to continue and 0 to quit :"))
			if c == 0:
				# thank() function calling
				thank(p1name, p2name, pp1, pp2)
				break


# Driver code
if __name__ == '__main__':

	# play() function calling
	play()


player 1, Please enter your name :A
Player 2 , Please enter your name: B
jumbled word is : ewatr
A Your Turn.
what is in your mind? water
Your score is : 1
jumbled word is : coonitndi
B Your turn.
what is in your mind? condition
Your Score is : 1
press 1 to continue and 0 to quit :0
A Your score is : 1
B Your score is : 1
Draw..Well Played guys..
Thanks for playing...


In [ ]:
import random
words = ['father','enterprise','science','programming','resistance','fiction','condition','reverse','water','board','geeks']
word = random.choice(words)
print(word)
jumbled = random.sample(word,len(word))
print(f"The jumbled word is {jumbled}")
guess = input("Type the guessed word:")
if guess==word:
  print("Correct guess")
else:
  print("Incorrect guess")


condition
The jumbled word is ['o', 't', 'i', 'd', 'o', 'n', 'c', 'n', 'i']
Type the guessed word:condition
Correct guess


In [ ]:
def fib(n):
  if n<=1:
    return n
  else:
    return fib(n-1) + fib(n-2)

n = int(input("Enter the number of terms:"))
for i in range(n):
  print(fib(i))

Enter the number of terms:5
0
1
1
2
3


In [ ]:
# Recursive Python function to solve the tower of hanoi

def TowerOfHanoi(n , source, destination, auxiliary):
	if n==1:
		print ("Move disk 1 from source",source,"to destination",destination)
		return
	TowerOfHanoi(n-1, source, auxiliary, destination)
	print ("Move disk",n,"from source",source,"to destination",destination)
	TowerOfHanoi(n-1, auxiliary, destination, source)

# Driver code
n = int(input("Enter the number of disks:"))
TowerOfHanoi(n,'A','B','C')
# A, C, B are the name of rods

Enter the number of disks:4
Move disk 1 from source A to destination C
Move disk 2 from source A to destination B
Move disk 1 from source C to destination B
Move disk 3 from source A to destination C
Move disk 1 from source B to destination A
Move disk 2 from source B to destination C
Move disk 1 from source A to destination C
Move disk 4 from source A to destination B
Move disk 1 from source C to destination B
Move disk 2 from source C to destination A
Move disk 1 from source B to destination A
Move disk 3 from source C to destination B
Move disk 1 from source A to destination C
Move disk 2 from source A to destination B
Move disk 1 from source C to destination B


In [ ]:
#Rock Paper Scissor Game Program in Python

# import random module
import random
# print multiline instruction
# performstring concatenation of string
print('Winning rules of the game ROCK PAPER SCISSORS are :\n'
      + "Rock vs Paper -> Paper wins \n"
      + "Rock vs Scissors -> Rock wins \n"
      + "Paper vs Scissors -> Scissor wins \n")

while True:

    print("Enter your choice \n 1 - Rock \n 2 - Paper \n 3 - Scissors \n")

    # take the input from user

    choice = int(input("Enter your choice :"))

    # OR is the short-circuit operator
    # if any one of the condition is true
    # then it return True value

    # looping until user enter invalid input
    while choice > 3 or choice < 1:
        choice = int(input('Enter a valid choice please '))

        # initialize value of choice_name variable
    # corresponding to the choice value
    if choice == 1:
        choice_name = 'Rock'
    elif choice == 2:
        choice_name = 'Paper'
    else:
        choice_name = 'Scissors'

        # print user choice
    print('User choice is \n', choice_name)
    print('Now its Computers Turn....')

    # Computer chooses randomly any number
    # among 1 , 2 and 3. Using randint method
    # of random module
    comp_choice = random.randint(1, 3)

    # looping until comp_choice value
    # is equal to the choice value
    while comp_choice == choice:
        comp_choice = random.randint(1, 3)

     # initialize value of comp_choice_name
    # variable corresponding to the choice value
    if comp_choice == 1:
        comp_choice_name = 'RocK'
    elif comp_choice == 2:
        comp_choice_name = 'Paper'
    else:
        comp_choice_name = 'Scissors'
    print("Computer choice is \n", comp_choice_name)
    print(choice_name, 'Vs', comp_choice_name)
    # we need to check of a draw
    if choice == comp_choice:
        print('Its a Draw', end="")
        result = "DRAW"
    # condition for winning
    if (choice == 1 and comp_choice == 2):
        print('paper wins =>', end="")
        result = 'Paper'
    elif (choice == 2 and comp_choice == 1):
        print('paper wins =>', end="")
        result = 'Paper'

    if (choice == 1 and comp_choice == 3):
        print('Rock wins =>\n', end="")
        result = 'Rock'
    elif (choice == 3 and comp_choice == 1):
        print('Rock wins =>\n', end="")
        result = 'RocK'

    if (choice == 2 and comp_choice == 3):
        print('Scissors wins =>', end="")
        result = 'Scissors'
    elif (choice == 3 and comp_choice == 2):
        print('Scissors wins =>', end="")
        result = 'Rock'
     # Printing either user or computer wins or draw
    if result == 'DRAW':
        print("<== Its a tie ==>")
    if result == choice_name:
        print("<== User wins ==>")
    else:
        print("<== Computer wins ==>")
    print("Do you want to play again? (Y/N)")
    # if user input n or N then condition is True
    ans = input().lower()
    if ans == 'n':
        break
# after coming out of the while loop
# we print thanks for playing
print("thanks for playing")

Winning rules of the game ROCK PAPER SCISSORS are :
Rock vs Paper -> Paper wins 
Rock vs Scissors -> Rock wins 
Paper vs Scissors -> Scissor wins 

Enter your choice 
 1 - Rock 
 2 - Paper 
 3 - Scissors 

Enter your choice :1
User choice is 
 Rock
Now its Computers Turn....
Computer choice is 
 Scissors
Rock Vs Scissors
Rock wins =>
<== User wins ==>
Do you want to play again? (Y/N)
Y
Enter your choice 
 1 - Rock 
 2 - Paper 
 3 - Scissors 

Enter your choice :2
User choice is 
 Paper
Now its Computers Turn....
Computer choice is 
 Scissors
Paper Vs Scissors
Scissors wins =><== Computer wins ==>
Do you want to play again? (Y/N)
N
thanks for playing


In [ ]:
s1 = 'Hello'
s2 = 'There'
s1 + s2

'HelloThere'

In [ ]:
s4 = input("Enter integer number:")
type(s4)
s4

Enter integer number:123


'123'

In [ ]:
fruit = 'banana'
letter  = fruit[0]
print(letter)
lastletter = fruit[-1]
print(lastletter)
length = len(fruit)
length

b
a


6

In [ ]:
#looping through the string
for i in fruit:
  print(i, end=" ")

b a n a n a 

In [ ]:
for index,letter in enumerate(fruit):
  print(f"Index:{index}, Letter:{letter}")

Index:0, Letter:b
Index:1, Letter:a
Index:2, Letter:n
Index:3, Letter:a
Index:4, Letter:n
Index:5, Letter:a


In [ ]:
a = 'Hello Good Morning LPU'
a[1:5]
a[:-1]

'Hello Good Morning LP'

In [ ]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [ ]:
print(a)
'Good' in a

Hello Good Morning LPU


True

In [ ]:
"Very" in a

False

In [ ]:
index = a.find('Good')
print(index)

6


In [ ]:
a.capitalize()

'Hello good morning lpu'

In [ ]:
a.title()

'Hello Good Morning Lpu'

In [ ]:
"the boy in a car".title()

'The Boy In A Car'

In [ ]:
a.replace("Good", "Wonderful")

'Hello Wonderful Morning LPU'

In [ ]:
b = '      Hello LPU '
b.lstrip()

'Hello LPU '

In [ ]:
b.rstrip()


'      Hello LPU'

In [ ]:
b.strip()

'Hello LPU'

In [ ]:
a= "riyaz@gmail.com"
print(a.split('@')[1])



gmail.com


In [ ]:
b = ('a')
print(type(b))

<class 'str'>


In [ ]:
b = ('a',)
print(type(b))

<class 'tuple'>


In [ ]:
a = (20, 40, 30, 60, 'Good', 'LPU')
print(a)
type(a)

(20, 40, 30, 60, 'Good', 'LPU')


tuple

In [ ]:
print(a[2])
print(a[-1])
print(a[:4])
print(a[:-1])
print(a[3:5])

30
LPU
(20, 40, 30, 60)
(20, 40, 30, 60, 'Good')
(60, 'Good')


In [ ]:
c = (1,2,3,4)
print(a + c)
print(c * 7)

(20, 40, 30, 60, 'Good', 'LPU', 1, 2, 3, 4)
(1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4)


In [ ]:
'Good' in a

True

In [ ]:
1 in c

True

In [ ]:
a == c

False

In [ ]:
a != c

True

In [ ]:

l1 = ['Python', 'is', 'fun']
a,b,c = l1
a
b
c

'fun'

In [ ]:
d, e = 1, 2
d

1

In [ ]:
e

2

In [ ]:
a = 20
b = 30
(a, b) = (b, a)
print(f"The value of a is {a} and b is {b}")

The value of a is 30 and b is 20


In [ ]:
[a, b] = [b, a]
print(a)

30


In [ ]:
tup = tuple(input('Tuple elements: ').split(' '))


Tuple elements: 1 2 3 4 5


In [ ]:
tup

('1', '2', '3', '4', '5')

In [ ]:
tup1 = tuple(input('Tuple elements: ').split(','))


Tuple elements: 1,2,3,4,5


In [ ]:
tup1

('1', '2', '3', '4', '5')

In [ ]:
list1 = list(input('Enter list elements: ').split(","))

Enter list elements: 1,2,3,5,6,Hello


In [ ]:
list1

['1', '2', '3', '5', '6', 'Hello']

In [ ]:
list2 = [1, 2, 3, 4]
print(type(list2))
tuple3 = tuple(list2)

<class 'list'>


In [ ]:
tuple3

(1, 2, 3, 4)

In [ ]:
a = list(input('Enter list elements: ').split(','))
b = tuple(a)
print(a,b)
c = input("Enter number to check:")
print(c in b)

Enter list elements: 1,2,3,4
['1', '2', '3', '4'] ('1', '2', '3', '4')
Enter number to check:2
True


In [ ]:
#Write a program to add an element to a tuple based on the user given values in a specific index. If the index is not in range, print the error message.

# Function to add an element at a specified index in a tuple
def add_to_tuple(tup, element, index):
    if index < 0 or index > len(tup):
        print("Error: Index is out of range.")
    else:
        # Split the tuple and insert the element
        new_tup = tup[:index] + (element,) + tup[index:]
        print("New tuple:", new_tup)

# Input tuple
my_tuple = (10, 20, 30, 40)

# User input for the element and index
new_element = input("Enter the element to add: ")
index = int(input(f"Enter the index (0 to {len(my_tuple)}): "))

# Call the function
add_to_tuple(my_tuple, new_element, index)

Enter the element to add: 25
Enter the index (0 to 4): 3
New tuple: (10, 20, 30, '25', 40)


In [ ]:
#10-09-2024

#Classes and Objects
#Create a class
class Employee:
  pass
#Create instance of the class
emp_1 = Employee()
#Take input
name = input("Enter your name: ")
#Assign name to the first instance
emp_1.name = name
#Assign salary to the first instance
emp_1.salary = 35000
#Print
print(emp_1.name)
print(emp_1.salary)

Enter your name: Raghu Nath
Raghu Nath
35000


In [ ]:
type(Employee)

type

In [ ]:
type(emp_1)
type(emp_1.salary)

int

In [ ]:
a = 20
print(type(a))

<class 'int'>


In [ ]:
# self is a "variable" in python , it is used to access attributes and methods of a class
#Self
class Manager:
  def __init__(self, name, department, salary):
    self.name = name
    self.department = department
    self.salary = salary

name = input("Enter your name: ")
department = input("Enter department name: ")
salary = int(input("Enter salary: "))
#Create object of the class
manager_1 = Manager(name, department, salary)
print(manager_1.name)
print(manager_1.department)
print(manager_1.salary)

Enter your name: raghu
Enter department name: cse
Enter salary: 60000
raghu
cse
60000


In [ ]:
class Car:
  def setName(self, name):
    self.name = name
  def getName(self):
    return self.name

Honda = Car()
carname = input("Enter the car name")
Honda.setName(carname)
print("Name of the car is: ",Honda.getName())


Enter the car nameJazz
Name of the car is:  Jazz


In [ ]:
# Define a class Student
class Student:
  def __init__(self, name, age):
    self.name = name
    self.age = age

name1 = input("Enter your name: ")
age1 = int(input("Enter the age: "))
name2 = input("Enter your name: ")
age2 = int(input("Enter the age: "))
# Create object of the class
s1 = Student(name, age)
s2 = Student(name, age)
print(s1.name1)
print(s1.age1)
print(s2.name2)
print(s2.age2)



Enter your name: raghu
Enter the age: 21
Enter your name: samy
Enter the age: 23


AttributeError: 'Student' object has no attribute 'name1'

In [ ]:
# 17-09-2024
# Birthdayboy problem

class BirthdayBoy:
  def __init__(self,current_year,birth_year,sibling_year):
    self.current_year = current_year
    self.birth_year = birth_year
    self.sibling_year = sibling_year
  def age(self):
    print(birth_year - sibling_year)
current_year = int(input("Enter current year:"))
birth_year = int(input("Enter birth year:"))
sibling_year = int(input("Enter sibling birth year:"))
m = BirthdayBoy(current_year,birth_year,sibling_year)
m.age()

Enter current year:2024
Enter birth year:2000
Enter sibling birth year:1992
8


In [ ]:
# 2nd problem
# Point Problem

class Point():
  def __init__(self,x1,y1,x2,y2):
    self.x1 = x1
    self.y1 = y1
    self.x2 = x2
    self.y2 = y2
  def slope(self):
    print((y2-y1)/(x2-x1))
x1=int(input("Enter x1 coordinate:"))
y1=int(input("Enter y1 coordinate:"))
x2=int(input("Enter x2 coordinate:"))
y2=int(input("Enter y2 coordinate:"))
m=Point(x1,y1,x2,y2)
m.slope()



Enter x1 coordinate:2
Enter y1 coordinate:3
Enter x2 coordinate:4
Enter y2 coordinate:6
1.5


In [ ]:
# Method Overloading

class Greeting:
  def sayHello(self,name=None,wish=None):
    if name is not None and wish is not None:
      print("Hello"+" "+name+" "+wish)
    elif name is not None and wish is None:
      print("Hello"+" "+name)
    else:
      print("Hello")

greet = Greeting()
a = input()
b = input()
greet.sayHello(a)
greet.sayHello(a,b)
greet.sayHello()


Raj
Good Morning
Hello Raj
Hello Raj Good Morning
Hello


In [ ]:
# Inheritance

class Car:
  def setenginemodel(self, engine):
    self.engine = engine
  def getenginemodel(self):
    return self.engine
class Honda(Car):
  def setcarmodel(self, model):
    self.model = model
  def getcarmodel(self):
    return self.model
mycar = Honda()
mycar.setenginemodel("EK-1")
mycar.setcarmodel("V6")
print("Car Details: ")
print(mycar.getenginemodel())
print(mycar.getcarmodel())




Car Details: 
EK-1
V6


In [ ]:
#Multi-level inheritance is possible in python language

class Person:
  def setname(self,name):
    self.name = name
  def getname(self):
    return self.name
class Student(Person):
  def setage(self,age):
    self.age = age
  def getage(self):
    return self.age
class Address(Student):
  def setaddress(self,address):
    self.address = address
  def getaddress(self):
    return self.address

s1 = Address()
Name = input("Enter Name:")
Age = int(input("Enter Age:"))
Place = input("Enter Place:")
s1.setage(Age)
s1.setname(Name)
s1.setaddress(Place)
print(s1.getname())
print(s1.getage())
print(s1.getaddress())


Enter Name:Raghu
Enter Age:21
Enter Place:Hyderabad
Raghu
21
Hyderabad


In [ ]:
# 19-09-2024
# Create shopping cart application using the concepts of object oriented programming

class ShoppingCart():
    def __init__(self):
        self.item = []

    def add_item(self,item_name,quantity,price):
        self.item.append({'item_name':item_name, 'quantity':quantity, 'price':price})

    def remove_item(self,item_name):
        for i in self.item:
            if i['item_name'] == item_name:
                self.item.remove(i)
                break

    def show_item(self):
        for i in self.item:
            total = 0
        for i in self.item:
            total = total + i['quantity'] * i['price']
            print(f"{i['item_name']} - {i['price']}")
        print(f"Total value of your Cart is: {total}")



In [ ]:
kart = ShoppingCart()


In [ ]:
kart.add_item(item_name='Orange',quantity=1,price=100)
kart.add_item(item_name='Lemon',quantity=1,price=10)
kart.add_item(item_name='Apple',quantity=1,price=50)
kart.add_item(item_name='Watermelon',quantity=1,price=30)

In [ ]:
kart.show_item()

Orange - 100
Lemon - 10
Apple - 50
Watermelon - 30
Total value of your Cart is: 190


In [ ]:
kart.remove_item('Orange')
kart.show_item()


Lemon - 10
Apple - 50
Watermelon - 30
Total value of your Cart is: 90


In [ ]:
# 24-09-2024
# Exception Handling

try:
  a=int(input("Enter 1st number(a): "))
  b=int(input("Enter 2nd number(b): "))
  div=a/b
  print(div)
except:
  print("Kindly Enter non zero value of b")


Enter 1st number(a): 1
Enter 2nd number(b): 0
Kindly Enter non zero value of b


In [ ]:
a=int(input("Enter 1st number(a): "))
b=int(input("Enter 2nd number(b): "))
div=a/b
print(div)

Enter 1st number(a): 4
Enter 2nd number(b): 0


ZeroDivisionError: division by zero

In [ ]:
try:
  a=int(input("Enter 1st number(a): "))
  b=int(input("Enter 2nd number(b): "))
  div=a/b
  print(div)
except ZeroDivisionError:
  print("Kindly Enter non zero value of b")
except ValueError:
  print("Invalid input kindly enter integer value")



Enter 1st number(a): four
Invalid input kindly enter integer value


In [ ]:
#Nesting: The process of placing one exception-handling routine within another. Nested routines first search for an exception handler within their scope, moving outward if not found. Exception-handling can be nested as deeply as needed to make your code safe.

#Build a python program on nested try-except block.

#Write program that repeatedly asks for a whole number input, handling exceptions and allowing users to retry or exit based on their choices.
#Firstly, used a while loop to keep prompting the user until they enter a valid whole number.
#Inside the loop, used a try block to attempt to convert the user's input to an integer.
#If the conversion raises a ValueError, print "you must enter a whole number!" and proceed to ask if the user wants to try again (y/n)?.
#If the user enters "y" (yes), the program should continue the loop.
#If the user enters "n" (no), or if they enter anything other than "y", the program should print "ok, see you next time!" and exit the loop.
#If the user interrupts the program with a keyboard interrupt (CTRL+C), catch the KeyboardInterrupt exception, print "You pressed Ctrl+C! See you next time!" and exit the loop.

In [ ]:
while True:
    try:
        # Asking the user for input
        user_input = input("Please enter a valid whole number: ")

        try:
            # Attempt to convert the input to an integer
            number = int(user_input)
            print(f"You entered the number: {number}")
            break  # Exit the loop if a valid number is entered

        except ValueError:
            # Handle invalid input (non-integer)
            print("You must enter a whole number!")
            retry = input("Would you like to try again? (y/n): ").strip().lower()

            if retry != 'y':
                print("Ok, see you next time!")
                break  # Exit the loop if user doesn't want to retry

    except KeyboardInterrupt:
        # Handle the keyboard interrupt (Ctrl+C)
        print("\nYou pressed Ctrl+C! See you next time!")
        break  # Exit the loop when Ctrl+C is pressed


Please enter a valid whole number: a
You must enter a whole number!
Would you like to try again? (y/n): n
Ok, see you next time!


In [ ]:
# Try Except and finally

try:
  a=int(input("Enter 1st number(a): "))
  b=int(input("Enter 2nd number(b): "))
  c=a+b
  d=a/b
  print("Try Successful")
except ArithmeticError:
  print("Arithmetic Error Occured")
except Exception:
  print("Exception occured")
finally:
  print("Executed in any condition")




Enter 1st number(a): 4
Enter 2nd number(b): 0
Arithmetic Error Occured
Executed in any condition


In [ ]:
# 2nd method of homework problem of lpu live

Try = True
while Try:
  try:
      value = abs(int(input("Enter whole number: ")))
  except ValueError:
    print("You must Enter the whole number")
    try:
      again = input("Try again (y/n): ")
    except:
      print("Ok, see you next time!")
      Try = False
    else:
      if str.upper(again) == 'N':
        Try = False
  except keyboardInterrupt:
    print("You have pressed CTRL + C! see you next time")
    Try=False
  else:
    print(value)
    Try = True


Enter whole number: 12
12
Enter whole number: aa
You must Enter the whole number
Try again (y/n): n


In [ ]:
try:
   age = int(input("Enter your age"))
   if age < 0:
      raise ValueError("Age cannot be negative")
   print(f"Age when doubled {age * 2}")
except ValueError:
    print("Age cannot be less than zero")
finally:
    print("Executed in any condition")

Enter your age-5
Age cannot be less than zero
Executed in any condition


In [ ]:
'''Write a user defined exception class and use it in the arithmetic division operation.
Define a class OurException with Exception as base class.
Inside this class define the constructor i.e. the __init__(self, message) (Here message is an argument that passed).
Set self.message = message.
Now define a class UsingUserException.
Start the try block.
Take input a and b from user.
Do a condition testing if b == 0, then raise the OurException with a message b should be greater than 0. (Here we call on the format(b) built in function of Python which prints the message with value of b in the correct format).
Do the operation a / b and store in d.
Print d saying division operation successful with result.
Open the except block with OurException with err as its instance.
Print "Raised an User defined Exception: " , err.message which prints the message that was raised. '''

# Defining the user-defined exception class
class OurException(Exception):
    def __init__(self, message):
        self.message = message

# Class to demonstrate using the user-defined exception
class UsingUserException:

    def division_operation():
        try:

            a = float(input("Enter the numerator (a): "))
            b = float(input("Enter the denominator (b): "))

            if b == 0:
                raise OurException("Error: Denominator should be greater than 0. You entered: {}".format(b))

            d = a / b
            print(f"Division operation successful with result: {d:.2f}")

        except OurException as err:
            print("Raised a User-defined Exception:", err.message)

UsingUserException.division_operation()

Enter the numerator (a): 10
Enter the denominator (b): 20
Division operation successful with result: 0.50


In [ ]:
# 08-10-2024
# numpy (numerical python) ----> used for numerical calculations
# pandas(panal data analysis) ----> series and data frames
# matplotlib ----> used for visualization purpose(exploratory analysis)
# scikit-learn(Scientific kit for machine learning)-----> contains all machine learning libraries

# Fundamentals of numpy

# NumPy : Array Object

import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
#od array
arr0 = np.array(50)
print("0D array is ",arr0)
arr1 = np.array([1,2,3,4])
print("1D array is ", arr1)
arr2 = np.array([[1,1,1,],[2,3,4]])
print("2D array is ", arr2)
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print("3D array is ", arr3)

0D array is  50
1D array is  [1 2 3 4]
2D array is  [[1 1 1]
 [2 3 4]]
3D array is  [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [ ]:
# od array
arr0 = np.array(50)
print("0D array is ",arr0)
# 1d array
arr1 = np.array([1,2,3,4])
print("1D array is ", arr1)
# 2d array
arr2 = np.array([[1,1,1,],[1,2,1]])
print("2D array is ", arr2)
# 3d array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print("3D array is ", arr3)

0D array is  50
1D array is  [1 2 3 4]
2D array is  [[1 1 1]
 [1 2 1]]
3D array is  [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)

(5,)
int64
5
8
1


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
new1D = new_arr.flatten()
print(new1D)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
t_new = new_arr.transpose()
print(t_new)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [ ]:
# Task

import numpy as np
temperatures = np.array([75.2,77.1,74.5,79.3,82.6,81.2,77.8,78.7])
print(temperatures.data)
print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)
print(temperatures.itemsize)
print(temperatures.ndim)

new_arr = temperatures.reshape(4,2)
print(new_arr)
new1D = new_arr.flatten()
print(new1D)
t_new = new_arr.transpose()
print(t_new)


(8,)
float64
8
8
1
[[75.2 77.1]
 [74.5 79.3]
 [82.6 81.2]
 [77.8 78.7]]
[75.2 77.1 74.5 79.3 82.6 81.2 77.8 78.7]
[[75.2 74.5 82.6 77.8]
 [77.1 79.3 81.2 78.7]]


In [ ]:
# 15-10-2024
# Arithmetic operations on numpy
# 1.1 Addition
import numpy as np
a = np.array([30, 20, 10])
b = np.array([10, 20, 30])
result = np.add(a, b)
print(result)

[40 40 40]


In [ ]:
# 1.2 Subtraction
a = np.array([[30, 20, 10], [50,70,90]])
b = np.array([[10, 20, 30], [40,30,50]])
result = np.subtract(a, b)
print(result)

[[ 20   0 -20]
 [ 10  40  40]]


In [ ]:
# 1.3 Multiplication
a = np.array([30, 20, 10])
b = np.array([10, 20, 30])
result = np.multiply(a, b)
print(result)

[300 400 300]


In [ ]:
# 1.4 Division
a = np.array([[30, 20, 10], [50,70,90]])
b = np.array([10,20,30])
result = np.divide(a, b)
print(result)

[[3.         1.         0.33333333]
 [5.         3.5        3.        ]]


In [ ]:
# 1.5 Power of
a = np.array([30, 20, 10])
b = np.array([10, 20, 30])
result = np.power(a, b)
print(result)

[     590490000000000 -2101438300051996672  5076944270305263616]


In [ ]:
# Statistical derivations
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
print(np.median(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))


4.0
6.333333333333333
6.944222218666553
48.22222222222222


In [ ]:
print(np.percentile(array, 85))

9.6


In [ ]:
s1 = np.array(["Hello", "World"])
s2 = np.array(["Welcome", "Learners"])
result = np.char.add(s1, s2)
print(result)

['HelloWelcome' 'WorldLearners']


In [ ]:
s3 = "Hello how are you"
print(s3)
z = np.char.replace(s3, "Hello", "Hi")
print(z)

Hello how are you
Hi how are you


In [ ]:
z1 = np.char.upper(z)
z2 = np.char.lower(z)
print(z1)
print(z2)

HI HOW ARE YOU
hi how are you


In [ ]:
# Task
# Array A: [15, 25, 35, 45, 55]
# Array B: [5, 10, 15, 20, 25]
import numpy as np
a = np.array([15, 25, 35, 45, 55])
b = np.array([5, 10, 15, 20, 25])
result = np.add(a, b)
print(result)
result = np.subtract(a, b)
print(result)
result = np.multiply(a, b)
print(result)
result = np.divide(a, b)
print(result)
result = np.power(a, b)
print(result)

[20 35 50 65 80]
[10 15 20 25 30]
[  75  250  525  900 1375]
[3.         2.5        2.33333333 2.25       2.2       ]
[             759375      95367431640625 3351328013648404811
 6545036034076902481 6038590913291571831]


In [ ]:
# Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]
array = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])
print(np.median(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))

57.0
57.0
28.722813232690143
825.0


In [ ]:
# String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
# String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
s1 = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
s2 = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])
result = np.char.add(s1, s2)
print(result)

['HelloWorld' 'DataAnalysis' 'Scienceis' 'ClassFun' 'Learners2023']


In [ ]:
# String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
z = np.char.upper(s1)
print(z)

['HELLO' 'DATA' 'SCIENCE' 'CLASS' 'LEARNERS']


In [ ]:
# String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
z = np.char.replace(s2,"World","India")
print(z)

['India' 'Analysis' 'is' 'Fun' '2023']


In [ ]:
# Indexing in numpy
# 1.1 Access Elements in the 1D NumPy Array
import numpy as np
array1d = np.array([1,2,3,4,5,6])
array2d = np.array([[1,2,3],[4,5,6]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array1d[3])
print(array2d[0, 2]) # third element of the 1st row of a 2D array
print(array2d[1, 1]) # second element of the 2nd row of a 2D array
print(array3d[1, 1, 0])
print(array3d[0,1,2])

4
3
5
10
6


In [ ]:
print(array1d)
print(array1d[-2])
print(array2d)
print(array2d[-1, -1])
print(array3d)
print(array3d[-1,-1,-1])

[1 2 3 4 5 6]
5
[[1 2 3]
 [4 5 6]]
6
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [ ]:
''' Problem Statement:
Create a 1D NumPy array with at least 10 elements
Create a 2D NumPy array with a minimum of 3 rows and 4 columns
Create a 3D NumPy array with at least 2 matrices, each containing 2 rows and 3 columns
Accessing Elements in Arrays
Access and print various elements from 1D, 2D, and, 3D using positive indexing
Perform and print some basic arithmetic operations (like addition, subtraction) using elements accessed from 1D, 2D, and, 3D arrays
Access and print elements using negative indices in all three arrays'''


import numpy as np

# Creating the 1D, 2D, and 3D arrays
array_1d = np.arange(10)  # 1D array with 10 elements
array_2d = np.arange(12).reshape(3, 4)  # 2D array with 3 rows and 4 columns
array_3d = np.arange(12).reshape(2, 2, 3)  # 3D array with 2 matrices, 2 rows, and 3 columns each

# Accessing elements using positive indexing
elem_1d_pos = array_1d[2]  # Accessing 3rd element in 1D array
elem_2d_pos = array_2d[1, 2]  # Accessing element at 2nd row, 3rd column in 2D array
elem_3d_pos = array_3d[1, 0, 2]  # Accessing element from 2nd matrix, 1st row, 3rd column in 3D array

# Arithmetic operations
add_result = elem_1d_pos + elem_2d_pos + elem_3d_pos
sub_result = elem_1d_pos - elem_2d_pos - elem_3d_pos

# Accessing elements using negative indexing
elem_1d_neg = array_1d[-1]  # Last element in 1D array
elem_2d_neg = array_2d[-2, -3]  # Element at 2nd last row, 3rd last column in 2D array
elem_3d_neg = array_3d[-1, -1, -2]  # Element from last matrix, last row, 2nd last column in 3D array

{
    "1D array": array_1d,
    "2D array": array_2d,
    "3D array": array_3d,
    "Positive indexing results": {
        "1D element": elem_1d_pos,
        "2D element": elem_2d_pos,
        "3D element": elem_3d_pos,
    },
    "Arithmetic results": {
        "Addition result": add_result,
        "Subtraction result": sub_result,
    },
    "Negative indexing results": {
        "1D element": elem_1d_neg,
        "2D element": elem_2d_neg,
        "3D element": elem_3d_neg,
    }
}



{'1D array': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 '2D array': array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 '3D array': array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]),
 'Positive indexing results': {'1D element': 2,
  '2D element': 6,
  '3D element': 8},
 'Arithmetic results': {'Addition result': 16, 'Subtraction result': -12},
 'Negative indexing results': {'1D element': 9,
  '2D element': 5,
  '3D element': 10}}

In [ ]:
# Slicing in 1D numpy arrays
import numpy as np
employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(employee_rating[1:7])

[4 3 5 6 8 9]


In [ ]:
Z = np.array([[11,22,33,44,55],[66,77,88,99,110]])
print(Z[0, 2:3])

[33]


In [ ]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
array2d = array1d.reshape(4,6)
array3d = array1d.reshape(2,3,4)
print(array1d)
print(array2d)
print(array3d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# 22-10-2024

'''Problem Statement:
Creating arrays for slicing:

Create a 1D NumPy array with at least 15 elements
Create a 2D NumPy array with a minimum of 4 rows and 5 columns
Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
Slicing 1D arrays:

Perform and demonstrate different slices on the 1D array, explore it using step values
Slicing 2D arrays:

Slice rows and columns separately and in combination
Slicing 3D arrays:

Perform slicing to access different matrices, rows within matrices, and elements within rows
Negative slicing:

Implement negative slicing on 1D, 2D, and 3D arrays
Compare the outcomes of negative slicing with positive slicing and explain the results.'''

import numpy as np

# Creating a 1D NumPy array with at least 15 elements
array_1d = np.arange(15)

# Creating a 2D NumPy array with a minimum of 4 rows and 5 columns
array_2d = np.arange(20).reshape(4, 5)

# Creating a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
array_3d = np.arange(24).reshape(2, 3, 4)

# --------------- Slicing 1D Array ---------------

# Slice from index 2 to 8
slice_1d_1 = array_1d[2:8]

# Slice with a step value of 2
slice_1d_2 = array_1d[::2]

# Slice from index 5 to the end
slice_1d_3 = array_1d[5:]

# --------------- Slicing 2D Array ---------------

# Slicing rows from index 1 to 3
slice_2d_rows = array_2d[1:3]

# Slicing columns from index 1 to 4
slice_2d_cols = array_2d[:, 1:4]

# Slicing specific rows and columns (row 1 to 3, columns 2 to 4)
slice_2d_combined = array_2d[1:3, 2:4]

# --------------- Slicing 3D Array ---------------

# Slicing the first matrix
slice_3d_matrix = array_3d[0]

# Slicing the first row of the second matrix
slice_3d_row = array_3d[1, 0]

# Slicing elements from the first row of the first matrix
slice_3d_elements = array_3d[0, 0, 1:3]

# --------------- Negative Slicing ---------------

# Negative slice on 1D array (last 5 elements)
neg_slice_1d = array_1d[-5:]

# Negative slicing on 2D array (last 2 rows and last 3 columns)
neg_slice_2d = array_2d[-2:, -3:]

# Negative slicing on 3D array (last matrix, last row, last 2 elements)
neg_slice_3d = array_3d[-1, -1, -2:]

# Print results
print("1D Array:", array_1d)
print("Slice from index 2 to 8:", slice_1d_1)
print("Slice with a step of 2:", slice_1d_2)
print("Slice from index 5 to end:", slice_1d_3)

print("\n2D Array:\n", array_2d)
print("Slicing rows from index 1 to 3:\n", slice_2d_rows)
print("Slicing columns from index 1 to 4:\n", slice_2d_cols)
print("Slicing rows 1 to 3 and columns 2 to 4:\n", slice_2d_combined)

print("\n3D Array:\n", array_3d)
print("Slicing first matrix:\n", slice_3d_matrix)
print("Slicing first row of second matrix:\n", slice_3d_row)
print("Slicing elements from first row of first matrix:", slice_3d_elements)

print("\nNegative Slicing")
print("Last 5 elements of 1D array:", neg_slice_1d)
print("Last 2 rows and last 3 columns of 2D array:\n", neg_slice_2d)
print("Last matrix, last row, last 2 elements of 3D array:", neg_slice_3d)


1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Slice from index 2 to 8: [2 3 4 5 6 7]
Slice with a step of 2: [ 0  2  4  6  8 10 12 14]
Slice from index 5 to end: [ 5  6  7  8  9 10 11 12 13 14]

2D Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Slicing rows from index 1 to 3:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]]
Slicing columns from index 1 to 4:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
Slicing rows 1 to 3 and columns 2 to 4:
 [[ 7  8]
 [12 13]]

3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Slicing first matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Slicing first row of second matrix:
 [12 13 14 15]
Slicing elements from first row of first matrix: [1 2]

Negative Slicing
Last 5 elements of 1D array: [10 11 12 13 14]
Last 2 rows and last 3 columns of 2D array:
 [[12 13 14]
 [17 18 19]]
Last matrix, last row, last 2 elements of 3D array: [22 23]


In [ ]:
'''Problem Statement:
You are working with a dataset in which each feature has different units and scales, which might affect the performance of your machine learning algorithm. Your task is to normalize the data so that each feature has a mean of 0 and a standard deviation of 1.

The dataset is a NumPy array with the following structure:
data = np.array([
[15, 2000, 10],
[20, 2200, 15],
[18, 2100, 12],
[25, 2300, 20],
[30, 2500, 25]
])
Write a Python code using NumPy to:
1. Normalize the dataset so that each feature (column) has a mean of 0 and a standard deviation of 1.
2. Verify the results by printing the mean and standard deviation of each column of the normalized data.
Expected Output:
1. The mean of each column after normalization should be approximately 0.
2. The standard deviation of each column after normalization should be 1.'''

import numpy as np

# Given dataset
data = np.array([
    [15, 2000, 10],
    [20, 2200, 15],
    [18, 2100, 12],
    [25, 2300, 20],
    [30, 2500, 25]
])

# Normalize the dataset
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

normalized_data = (data - mean) / std

# Verify the results by calculating the mean and standard deviation of the normalized data
normalized_mean = np.abs(np.round(np.mean(normalized_data, axis=0)))
normalized_std = np.round(np.std(normalized_data, axis=0))

print("Normalized Data:")
print(normalized_data)
print("Mean of each column after normalization:", normalized_mean)
print("Standard deviation of each column after normalization:", normalized_std)


Normalized Data:
[[-1.24197138 -1.27872403 -1.17160324]
 [-0.30108397 -0.11624764 -0.25628821]
 [-0.67743894 -0.69748583 -0.80547723]
 [ 0.63980344  0.46499055  0.65902682]
 [ 1.58069085  1.62746694  1.57434186]]
Mean of each column after normalization: [0. 0. 0.]
Standard deviation of each column after normalization: [1. 1. 1.]


In [ ]:
# Pandas
''' open source library
used for manipulating data

Purpose of pandas
--> intrinsic data
advantages of pandas
--> powerful data structure '''

import pandas as pd
#Create Series
data = [7,8,9,10,11,12]
series = pd.Series(data)
print(series)
#Series with specific index
index = ['a','b','c','d','e','f']
series_with_index = pd.Series(data,index = index)
print(series_with_index)
mydict = {'a':1, 'b':2, 'c':3, 'd':4}
series_with_dict = pd.Series(mydict)
print(series_with_dict)


0     7
1     8
2     9
3    10
4    11
5    12
dtype: int64
a     7
b     8
c     9
d    10
e    11
f    12
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
first_n_rows = series.head(3)
print(first_n_rows)
last_n_rows = series.tail(3)
print(last_n_rows)
stats = series.describe()
print(stats)
unique_val = series.unique()
print(unique_val)

0    7
1    8
2    9
dtype: int64
3    10
4    11
5    12
dtype: int64
count     6.000000
mean      9.500000
std       1.870829
min       7.000000
25%       8.250000
50%       9.500000
75%      10.750000
max      12.000000
dtype: float64
[ 7  8  9 10 11 12]


In [ ]:
sum_series = series + series
print(sum_series)
#Applying function to each element
square_series = series.apply(lambda x: x**2)
print(square_series)
s = series + series_with_index
null_values = s.isnull()
print(null_values)
fill_null_val = s.fillna(0)
print(fill_null_val)
print(series.sort_values())

0    14
1    16
2    18
3    20
4    22
5    24
dtype: int64
0     49
1     64
2     81
3    100
4    121
5    144
dtype: int64
0    True
1    True
2    True
3    True
4    True
5    True
a    True
b    True
c    True
d    True
e    True
f    True
dtype: bool
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
a    0.0
b    0.0
c    0.0
d    0.0
e    0.0
f    0.0
dtype: float64
0     7
1     8
2     9
3    10
4    11
5    12
dtype: int64


In [ ]:
#Select element greater than 10
greater = series[series > 10]
print(greater)
greater = series[series != 10]
print(greater)
greater = series[(series > 10) & (series < 12)]
print(greater)
select_by_index = series.iloc[[1,2,3]]
print(select_by_index)
series.iloc[1:4]
str_series = pd.Series(['apple','banana','kivi','Guava','blueberry','orange'])
str_query = str_series[str_series.str.startswith('b')]
print(str_query)

4    11
5    12
dtype: int64
0     7
1     8
2     9
4    11
5    12
dtype: int64
4    11
dtype: int64
1     8
2     9
3    10
dtype: int64
1       banana
4    blueberry
dtype: object


In [ ]:
# 24-10-2024
